Import('env')
src = [
    'common/common.c',
    'common/circular_doubly_linked_list.c',
    'common/linked_async_framework.c',
    'common/async_call.c',
    'common/sw_timer.c',
    'calendar/calendar.c',
    'crc/crc16.c',
    'debug/log.c',
    'debug/ls_dbg.c',
    'debug/$BASE_ARCH/$COMPILER/ls_dbg_asm.S',
    'debug/RTT/SEGGER_RTT_printf.c',
    'debug/RTT/SEGGER_RTT.c',
    'static_buffer/linked_buffer.c',
    'static_buffer/fifo.c',
    'tinyfs/tinyfs_nvm.c',
    'tinyfs/tinyfs_write_cache.c',
    'tinyfs/tinyfs.c',
    'tinycrypt/lib/source/sha256.c',
    'tinycrypt/lib/source/utils.c',
    'adpcm/adpcm.c',
    'micro-ecc/uECC.c',
    'ble/ble_common_api.c',
]

if env['IC'] != 'le501x' and env['IC'] != 'gemini':
    src += ['ble/ll_buf.c']

inc = [
    'crc',
    'debug',
    'debug/RTT',
    'static_buffer',
    'tinyfs',
    'tinycrypt/lib/include',
    'ble',
    'ble/prf',
    'ble/ll',
    'common',
    'adpcm',
    'calendar',
    'micro-ecc',
]
src_files = File(env.subst(src))
inc_dirs = Dir(inc)
Return("src_files","inc_dirs")