soft_version: "v1.0"
mtb_version: 4
chip: cb2201        # cb2201 / cb6501
signature_type: RSA # RSA / ECC
digest_type: SHA256 # SHA1 / MD5 / SHA224 / SHA256 / SHA384 / SHA512
diff:
  ram_buf: 50      #DEC     KB   ( max ram need)
  flash_buf: 4     #DEC     KB   ( buffer size)
  flash_sector: 4096 #DEC     byte ( flash sector)
  diff_mode: 010    #BIN

flash:
  base_address: 0x18000000 #flash base address
  sector: 4096       # Bytes
  size: 524288      # $(sector count) * sector
partitions:
  - { name: init,    address: 0x18000000, size: 0x007000, update: NONE }
  - { name: kv,      address: 0x18007000, size: 0x002000, update: NONE }
  - { name: imtb,    address: 0x18009000, size: 0x002000, update: NONE }
  #- { name: prim,    address: 0x1800b000, size: 0x045000, update: FULL }
  #- { name: misc,    address: 0x18050000, size: 0x014000, update: NONE }
  - { name: prim,    address: 0x1800b000, size: 0x02b000, update: FULL }
  - { name: misc,    address: 0x18036000, size: 0x02e000, update: NONE }
  - { name: stack,   address: 0x18064000, size: 0x01b000, update: NONE }
  - { name: otp,     address: 0x1807f000, size: 0x001000, update: NONE }
