mtb_version: 4
chip: TG7120B
diff:
  digest_type: SHA1
  signature_type: AES_128_CCM
  fota_version: 0
  ram_buf: 10      #DEC     KB   ( max ram need)
  flash_buf: 4     #DEC     KB   ( buffer size)
  flash_sector: 4096 #DEC     byte ( flash sector)
  diff_mode: 010    #BIN

flash:
  base_address: 0x11000000       # 存储基地址，比如FLASH的基地址
  run_base_address: 0x1fff2000   # 运行基地址，一般指SDRAM的基地址
  sector: 4096       # Bytes
  size: 524288      # $(sector count) * sector
partitions:
  - { name: bomtb,   address: 0x11002000, size: 0x002000 }
  - { name: FCDS,    address: 0x11004000, size: 0x001000 }
  - { name: imtb,    address: 0x11005000, size: 0x002000 }
  - { name: boot,    address: 0x11009000, size: 0x008000, verify: true }
  - { name: prim,    address: 0x11011000, size: 0x035000, verify: true, update: FULL,}
  - { name: misc,    address: 0x11046000, size: 0x037000 }
  - { name: kv,      address: 0x1107D000, size: 0x003000 }
