#ifndef __SIG_MODEL_OPCODE_H__
#define __SIG_MODEL_OPCODE_H__

#define OP_GENERIC_ONOFF_GET BT_MESH_MODEL_OP_2(0x82, 0x01)
#define OP_GENERIC_ONOFF_SET BT_MESH_MODEL_OP_2(0x82, 0x02)
#define OP_GENERIC_ONOFF_SET_UNACK BT_MESH_MODEL_OP_2(0x82, 0x03)
#define OP_GENERIC_ONOFF_STATUS BT_MESH_MODEL_OP_2(0x82, 0x04)

#define OP_GENERIC_LEVEL_GET BT_MESH_MODEL_OP_2(0x82, 0x05)
#define OP_GENERIC_LEVEL_SET BT_MESH_MODEL_OP_2(0x82, 0x06)
#define OP_GENERIC_LEVEL_SET_UNACK BT_MESH_MODEL_OP_2(0x82, 0x07)
#define OP_GENERIC_LEVEL_STATUS BT_MESH_MODEL_OP_2(0x82, 0x08)
#define OP_GENERIC_DALTA_SET BT_MESH_MODEL_OP_2(0x82, 0x09)
#define OP_GENERIC_DALTA_SET_UNACK BT_MESH_MODEL_OP_2(0x82, 0x0a)
#define OP_GENERIC_MOVE_SET BT_MESH_MODEL_OP_2(0x82, 0x0b)
#define OP_GENERIC_MOVE_SET_UNACK BT_MESH_MODEL_OP_2(0x82, 0x0c)

//Scene Server Model
#define OP_GENERIC_SCENE_GET BT_MESH_MODEL_OP_2(0x82, 0x41)
#define OP_GENERIC_SCENE_RECALL BT_MESH_MODEL_OP_2(0x82, 0x42)
#define OP_GENERIC_SCENE_RECALL_UNACK BT_MESH_MODEL_OP_2(0x82, 0x43)
#define OP_GENERIC_SCENE_STATUS BT_MESH_MODEL_OP_1(0x5E)
#define OP_GENERIC_SCENE_REGISTER_GET BT_MESH_MODEL_OP_2(0x82, 0x44)
#define OP_GENERIC_SCENE_REGISTER_STATUS BT_MESH_MODEL_OP_2(0x82, 0x45)
//Scene Setup Server Model
#define OP_GENERIC_SCENE_STORE BT_MESH_MODEL_OP_2(0x82, 0x46)
#define OP_GENERIC_SCENE_STORE_UNACK BT_MESH_MODEL_OP_2(0x82, 0x47)
#define OP_GENERIC_SCENE_DELETE BT_MESH_MODEL_OP_2(0x82, 0x9E)
#define OP_GENERIC_SCENE_DELETE_UNACK BT_MESH_MODEL_OP_2(0x82, 0x9F)

#define OP_GENERIC_LIGHTNESS_GET BT_MESH_MODEL_OP_2(0x82, 0x4b)
#define OP_GENERIC_LIGHTNESS_SET BT_MESH_MODEL_OP_2(0x82, 0x4c)
#define OP_GENERIC_LIGHTNESS_SET_UNACK BT_MESH_MODEL_OP_2(0x82, 0x4d)
#define OP_GENERIC_LIGHTNESS_STATUS BT_MESH_MODEL_OP_2(0x82, 0x4e)

#define OP_GENERIC_LIGHT_CTL_GET BT_MESH_MODEL_OP_2(0x82, 0x5d)
#define OP_GENERIC_LIGHT_CTL_SET BT_MESH_MODEL_OP_2(0x82, 0x5e)
#define OP_GENERIC_LIGHT_CTL_SET_UNACK BT_MESH_MODEL_OP_2(0x82, 0x5f)
#define OP_GENERIC_LIGHT_CTL_STATUS BT_MESH_MODEL_OP_2(0x82, 0x60)

#endif
